# Generated by Django 5.2.4 on 2025-07-20 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_alter_todoitem_options_alter_todoitem_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ('id',), 'verbose_name': 'ToDo name'},
        ),
    ]
