# Generated by Django 5.2.4 on 2025-07-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0008_todoitem_execute_time_alter_todoitem_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='remind_before',
            field=models.IntegerField(default=15),
        ),
    ]
