services:
#  maildev:
#    image: maildev/maildev
#    environment:
#      - TZ=Europe/Moscow
#      - MAILDEV_WEB_PORT=1080
#      - MAILDEV_SMTP_PORT=1025
#    ports:
#      - "8080:1080"
#      - "1025:1025"
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "1m"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  redis_data: