services:
#  maildev:
#    image: maildev/maildev
#    environment:
#      - TZ=Europe/Moscow
#      - MAILDEV_WEB_PORT=1080
#      - MAILDEV_SMTP_PORT=1025
#    ports:
#      - "8080:1080"
#      - "1025:1025"
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "1m"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq_dj
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest_dj"
      RABBITMQ_DEFAULT_PASS: "guest_dj"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq_dj

volumes:
  rabbitmq-data: